name: dotnet-build

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'   

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3   

      - name: Mensagem personalizada
        run: echo "Executando o build .NET - script personalizado"
